import { useState, type ChangeEvent, type DragEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  EXAMPLE_STATBLOCK_JSON,
  parseMonsterJson,
} from '@shared/importAdapter.ts'
import { saveImage, saveMonster } from '@/lib/storage.ts'
import { saveImageFromDataUrl } from '@/lib/importExport.ts'
import { PromptGuide } from './PromptGuide.tsx'

export function PasteJsonEditor() {
  const navigate = useNavigate()
  const [jsonText, setJsonText] = useState('')
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [imagePreview, setImagePreview] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isDragging, setIsDragging] = useState(false)

  function handleFileSelection(file: File | undefined) {
    if (!file) return
    if (!file.type.startsWith('image/')) {
      setError('Please select an image file (PNG, JPEG, WebP, etc.).')
      return
    }
    setImageFile(file)
    if (imagePreview) URL.revokeObjectURL(imagePreview)
    setImagePreview(URL.createObjectURL(file))
  }

  function handleFileChange(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    handleFileSelection(file)
  }

  function handleDragOver(e: DragEvent<HTMLDivElement>) {
    e.preventDefault()
    setIsDragging(true)
  }

  function handleDragLeave(e: DragEvent<HTMLDivElement>) {
    e.preventDefault()
    setIsDragging(false)
  }

  function handleDrop(e: DragEvent<HTMLDivElement>) {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer.files?.[0]
    handleFileSelection(file)
  }

  function handleClearImage() {
    setImageFile(null)
    if (imagePreview) URL.revokeObjectURL(imagePreview)
    setImagePreview(null)
  }

  function handleFormatJson() {
    setError(null)
    if (!jsonText.trim()) return
    try {
      const parsed = parseMonsterJson(jsonText)
      setJsonText(JSON.stringify(parsed.monster, null, 2))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Invalid JSON format')
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError(null)

    if (!jsonText.trim()) {
      setError('Please paste JSON statblock data.')
      return
    }

    setIsSubmitting(true)
    try {
      const { monster, image: embeddedImage } = parseMonsterJson(jsonText)

      let imageBlobId: string | null = null

      // If user uploaded a new image file, use that
      if (imageFile) {
        imageBlobId = await saveImage(imageFile, imageFile.type)
      } else if (embeddedImage?.dataUrl) {
        // Otherwise check if JSON wrapper contained embedded image
        imageBlobId = await saveImageFromDataUrl(
          embeddedImage.dataUrl,
          embeddedImage.mime,
        )
      }

      const finalMonster = {
        ...monster,
        imageBlobId: imageBlobId ?? monster.imageBlobId ?? null,
        updatedAt: new Date().toISOString(),
      }

      await saveMonster(finalMonster)
      navigate(`/monster/${finalMonster.id}`)
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to parse or save the monster JSON.',
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <form
      onSubmit={handleSubmit}
      className="space-y-5 rounded border border-oxblood/40 bg-statblock p-6"
    >
      <div>
        <h2 className="font-display text-2xl uppercase text-oxblood">
          Paste Monster JSON
        </h2>
        <p className="mt-1 text-sm italic text-ink/75">
          Paste a JSON statblock generated by your favorite AI or tool, attach an optional image, and inscribe it into your bestiary.
        </p>
      </div>

      <PromptGuide
        onFillExample={() => {
          setJsonText(JSON.stringify(EXAMPLE_STATBLOCK_JSON, null, 2))
          setError(null)
        }}
      />

      {error ? (
        <div
          role="alert"
          className="rounded border border-oxblood/60 bg-oxblood/10 p-3 text-sm text-oxblood-dark"
        >
          <strong>Error: </strong>
          {error}
        </div>
      ) : null}

      <div>
        <div className="mb-1 flex items-center justify-between">
          <label
            htmlFor="monster-json-input"
            className="font-display text-xs uppercase tracking-wide text-oxblood"
          >
            Monster JSON <span className="text-oxblood">*</span>
          </label>
          <div className="flex gap-2 text-xs">
            <button
              type="button"
              onClick={handleFormatJson}
              className="text-oxblood underline hover:text-oxblood-dark"
            >
              Format JSON
            </button>
            <button
              type="button"
              onClick={() => {
                setJsonText('')
                setError(null)
              }}
              className="text-ink/60 underline hover:text-ink"
            >
              Clear
            </button>
          </div>
        </div>
        <textarea
          id="monster-json-input"
          required
          rows={14}
          value={jsonText}
          onChange={(e) => setJsonText(e.target.value)}
          placeholder={`{\n  "name": "Samogitian Knight",\n  "size": "Medium",\n  "type": "humanoid",\n  "alignment": "chaotic neutral",\n  "ac": "16 (half plate)",\n  "hp": 45,\n  "hit_dice": "6d8+18",\n  "speed": "30 ft.",\n  "stats": [18, 14, 14, 10, 12, 12],\n  ...\n}`}
          className="w-full rounded border border-oxblood/40 bg-parchment p-3 font-mono text-xs text-ink focus:border-oxblood focus:outline-none"
          spellCheck={false}
        />
      </div>

      <div className="space-y-2">
        <span className="font-display text-xs uppercase tracking-wide text-oxblood">
          Optional Illustration / Portrait
        </span>

        <div
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          className={`flex flex-col items-center justify-center rounded border-2 border-dashed p-4 text-center transition ${
            isDragging
              ? 'border-oxblood bg-oxblood/10'
              : 'border-oxblood/30 bg-parchment/40 hover:border-oxblood/50'
          }`}
        >
          {imagePreview ? (
            <div className="space-y-3">
              <img
                src={imagePreview}
                alt="Selected monster artwork preview"
                className="mx-auto max-h-56 rounded border border-oxblood/30 object-contain shadow-sm"
              />
              <div className="flex justify-center gap-3">
                <label className="cursor-pointer text-xs font-display uppercase tracking-wide text-oxblood underline hover:text-oxblood-dark">
                  Change Image
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileChange}
                    className="hidden"
                  />
                </label>
                <button
                  type="button"
                  onClick={handleClearImage}
                  className="text-xs font-display uppercase tracking-wide text-oxblood/80 underline hover:text-oxblood"
                >
                  Remove Image
                </button>
              </div>
            </div>
          ) : (
            <div className="space-y-2 py-2">
              <p className="text-sm text-ink/75">
                Drag &amp; drop an illustration file here, or browse from your device
              </p>
              <label className="inline-block cursor-pointer rounded border border-oxblood bg-parchment px-3 py-1.5 font-display text-xs uppercase tracking-wider text-oxblood transition hover:bg-oxblood hover:text-parchment">
                Browse Image
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleFileChange}
                  className="hidden"
                />
              </label>
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center justify-end gap-3 pt-2">
        <button
          type="submit"
          disabled={isSubmitting}
          className="rounded bg-oxblood px-5 py-2.5 font-display tracking-wider text-parchment uppercase shadow transition hover:bg-oxblood-dark disabled:opacity-60"
        >
          {isSubmitting ? 'Inscribing…' : 'Inscribe into Bestiary'}
        </button>
      </div>
    </form>
  )
}
